### ISSUE TITLE
Optimized bundle-size for projects

### ISSUE THREAD

**Issue by Silind** [Silind-Software/direflow#1]
Enhance the build-script such that all shared dependencies between components are hoisted to project level.

Steps:
- [ ] Create script for detecting shared dependencies across components
- [ ] Configure Webpack to chunk components during build to remove shared third party libraries
- [ ] Include in project build via. Webpack

**Comment by Alifarmand** [comment]
I am waiting for this ticket. This will do a big difference in bundle size.

**Comment by Silind** [comment]
In [version 2.0.0](https://github.com/Silind-Software/direflow/issues/17), the "Direflow Project" feature will become deprecated.
Instead, support for creating multiple Web Components from the same build setup is going to be supported.

This issue is no longer relevant.
