### ISSUE TITLE
Error : Cannot read property 'forEach' of undefined CustomComponent.js

### ISSUE THREAD

**Issue by vksantoshsunny** [Silind-Software/direflow#10]
![image](https://user-images.githubusercontent.com/26269568/69281676-93359980-0c4d-11ea-9779-59f89f632d21.png)

Set up the app and when I run it I see this error in console.

**Comment by Silind** [comment]
Hi @vksantoshsunny 
Thank you for creating this issue.

I'm not able to reproduce the problem.
Did you change the `direflow-config.js` file after setting up the component?
If so, can you post how it looks now?

**Comment by Silind** [comment]
I have created a new patch version including some additional null-checking when extracting plugins.
Hopefully, that should solve the issue you are experiencing above.

Kindly try to upgrade your version of `direflow-component` to `1.0.19`, or install the latest version of `direflow-cli` and create your component again.
If this problem persists, please let me know in this issue.
