### ISSUE TITLE
Bundle all dependencies including React

### ISSUE THREAD

**Issue by saraivinha85** [Silind-Software/direflow#102]
**Is your feature request related to a problem? Please describe.**  
I develop in a restricted environment and my production app cannot download libraries from the internet in runtime. I would like an option to bundle all dependencies (including react) when I build the webcomponent

**Describe the solution you'd like**  
Pass a flag to the build script to bundle all dependencies

**Comment by Silind** [comment]
Hi @saraivinha85 
Thanks for creating an issue.

You are not the first to request offline support, so this is definitely something that we will look into.
There should be an issue build option, just as you suggest.

Until then, please see [this answer](https://github.com/Silind-Software/direflow/issues/86#issuecomment-592940718) on how to gain offline support.

**Comment by Silind** [comment]
Hi @saraivinha85 
In version 3.4.5 we have introduced a way to turn off lazyloading of React, and include React in the bundle instead.

In the `direflow-webpack.js` file:
```javascript
// This will disable lazyloading of React and ReactDOM.
module.exports = (config, env) => ({
  ...webpackConfig(config, env, {
    react: false,
    reactDOM: false,
  }),
});
```
```javascript
// This will make Direflow use a custom path to a CDN.
module.exports = (config, env) => ({
  ...webpackConfig(config, env, {
    react: 'https://my-cdn.com/react.js',
    reactDOM: 'https://my-cdn.com/react-dom.js',
  }),
});
```
