### ISSUE TITLE
Use slot to get web component content

### ISSUE THREAD

**Issue by nkrmr** [Silind-Software/direflow#114]
**Describe the bug**  
I'm trying to pass the children content of the web component to my React component with slot (https://developer.mozilla.org/en-US/docs/Web/Web_Components/Using_templates_and_slots)

```javascript
    <webcomponent-tooltip content="Tooltip content">
      <div slot="tootltip-text">Test children</div>
    </webcomponent-tooltip>
```
In my App.
```javascript
  return (
    <div
      style={{
        display: "inline-block",
        borderBottom: "1px dotted black",
        cursor: "pointer"
      }}
    >
      <slot name="tootltip-text" />
    </div>
  );
```
**Expected behavior**  
I want to get the children content of the web component to my React component.

**Comment by Silind** [comment]
Hi @nkrmr 
Thanks for creating this issue.
I'm not able to reproduce this problem - using the default demo content that ships with Direflow, everything works as expected.

Can you make a repository that showcases this issue so I can investigate?
Thanks in advance.

**Comment by Silind** [comment]
I've been looking into this issue, given access to a repository by @nkrmr. 
This seems to be related to initial attributes.

If an attribute is set on the Custom Element, the slotted element seems to be swallowed and never slotted into the Direflow Component.

We will look into this bug asap.
