### ISSUE TITLE
webpack version issue

### ISSUE THREAD

**Issue by BastianMa** [Silind-Software/direflow#115]
$npm install -g direflow-cli@latest
$direflow --version // 3.4.6
// OS: Windows 10 64Bit

$direflow create
- typescript
- eslint

$npm install
$npm run start

Errormessage:

`
There might be a problem with the project dependency tree.
It is likely not a bug in Create React App, but something you need to fix locally.

The react-scripts package provided by Create React App requires a dependency:

  "webpack": "4.42.0"

Don't try to install it manually: your package manager does it automatically.
However, a different version of webpack was detected higher up in the tree:

  C:\Projekte\test\346-component\node_modules\webpack (version: 4.42.1)

Manually installing incompatible versions is known to cause hard-to-debug issues.

If you would prefer to ignore this check, add SKIP_PREFLIGHT_CHECK=true to an .env file in your project.
That will permanently disable this message but you might encounter other issues.

To fix the dependency tree, try following the steps below in the exact order:

  1. Delete package-lock.json (not package.json!) and/or yarn.lock in your project folder.
  2. Delete node_modules in your project folder.
  3. Remove "webpack" from dependencies and/or devDependencies in the package.json file in your project folder.
  4. Run npm install or yarn, depending on the package manager you use.

In most cases, this should be enough to fix the problem.
If this has not helped, there are a few other things you can try:

  5. If you used npm, install yarn (http://yarnpkg.com/) and repeat the above steps with it instead.
     This may help because npm has known issues with package hoisting which may get resolved in future versions.

  6. Check if C:\Projekte\test\346-component\node_modules\webpack is outside your project directory.
     For example, you might have accidentally installed something in your home folder.

  7. Try running npm ls webpack in your project folder.
     This will tell you which other package (apart from the expected react-scripts) installed webpack.

If nothing else helps, add SKIP_PREFLIGHT_CHECK=true to an .env file in your project.
That would permanently disable this preflight check in case you want to proceed anyway.

P.S. We know this message is long but please read the steps above :-) We hope you find them helpful!
`

**Comment by Silind** [comment]
Hi @BastianMa 
Thanks for creating this issue 👍 

We are aware that there's a version mismatch, and we're currently working on a solution to keep the versions of Wepback in sync.

For now, simply add a `.env` file in your root folder, containing this line:
```
SKIP_PREFLIGHT_CHECK=true
```

That will solve the problem.

**Comment by mckennasoftware** [comment]
In my case my global Node_Modules had a WebPack folder in it that was causing this same issue. So the steps given by npm weren't working for me. 

Once I deleted the folder npm run start worked as expected. 

If you are having trouble with the given solution I recommend checking your global Node_Modules

**Comment by Mrakorus** [comment]
Try "npm install webpack@4.42.0 --save-dev" it worked for me.

**Comment by merlox** [comment]
To fix that issue in my case I had to uninstall webpack GLOBALLY and then install the required version globally.

1. npm uninstall -g webpack
2. npm i -g webpack@4.42.0

**Comment by ramilabbaszade** [comment]
> To fix that issue in my case I had to uninstall webpack GLOBALLY and then install the required version globally.
> 
>     1. `npm uninstall -g webpack`
> 
>     2. `npm i -g webpack@4.42.0`

Thanks. It worked for me and permanently fixed

**Comment by niyo2** [comment]
> > To fix that issue in my case I had to uninstall webpack GLOBALLY and then install the required version globally.
> > ```
> > 1. `npm uninstall -g webpack`
> > 
> > 2. `npm i -g webpack@4.42.0`
> > ```
> 
> Thanks. It worked for me and permanently fixed

**Comment by IsoftTech** [comment]
> To fix that issue in my case I had to uninstall webpack GLOBALLY and then install the required version globally.
> 
> 1. `npm uninstall -g webpack`
> 2. `npm i -g webpack@4.42.0`

This is sure going to work
