### ISSUE TITLE
ShadowDom/Material-UI-Plugin: Styles not added to same Components on one Page

### ISSUE THREAD

**Issue by BastianMa** [Silind-Software/direflow#121]
If you add the same Component twice on the same Page - and have ShadowDom and Material-UI-Plugin active, JSS-Styles are only added to one Component:

![image](https://user-images.githubusercontent.com/45563198/78009571-82a2d780-7341-11ea-9e08-548e294dc6b5.png)

**Comment by Silind** [comment]
Nice catch 👍
I was able to reproduce this.
This is definitely a bug. We will look into this shortly.

**Comment by nicocunin** [comment]
Hi,
I've got the solution, we simply need to provide a new SheetManager for each webcomponent:
```
return [<StylesProvider jss={jss} sheetsManager={new Map()}>{app}</StylesProvider>, insertionPoint];
```
You can assign me the ticket I'll provide a PR.

**Comment by Silind** [comment]
You're assigned, @nicocunin, thanks a lot :+1: 
Note that the plugins now follow this [new structure](https://github.com/Silind-Software/direflow/wiki/Direflow-Plugins).
