### ISSUE TITLE
IE11 Promise polyfill

### ISSUE THREAD

**Issue by lucabro81** [Silind-Software/direflow#122]
I've added all import specified in your doc for ie11 compatibility, building the test component, direflow-test:

```
import 'react-app-polyfill/ie11';
import 'react-app-polyfill/stable';
import 'abortcontroller-polyfill/dist/abortcontroller-polyfill-only';
import 'proxy-polyfill';
```

but ie11 throw an error:

```
SCRIPT5009: 'Promise' is undefined
direflowBundle.js (2,71682)
SCRIPT5009: 'Promise' is undefined
direflowBundle.js (2,218478)
```

I've tried to add also promise polyfill from core-js with:

`import 'core-js/features/promise';`

but same error

**Comment by mfreville** [comment]
If I can add information I have this error on IE 11 too :
Syntax error on direflowBundle.js (1135,34) when I launch a new direflow project (3.4.9)
![image](https://user-images.githubusercontent.com/34126107/79216603-c1f71b00-7e4d-11ea-8f86-eb5ea9fb42c9.png)

Even I had the polyfills.

Kind regards,
MF

**Comment by Silind** [comment]
Thanks, @lucabro81 and @mfreville.
We will be looking into this :+1: 

Can I ask you:
- Does this occur when included a build version of Direflow, or on development? Or both?
- Have you added 'IE 11' to `browserlist` in `package.json` as [described here](https://direflow.io/additional#ie-11-support)?

**Comment by mfreville** [comment]
Hey,

For me it appears on both after add polyfills and IE11 to the browser.

MF.

**Comment by Pantalaimon** [comment]
Hello,

I have the same issue, in development and production, with polyfills imported and "IE 11" in browserlist as instructed in the documentation.

I tried to quickfix this by adding a babel-polyfill script tag in the head of the index.html. This changed the error to :
```
Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
   at createFiberFromTypeAndProps (http://localhost:3000/direflowBundle.js:60479:19)
   at createFiberFromElement (http://localhost:3000/direflowBundle.js:60501:7)
   at reconcileSingleElement (http://localhost:3000/direflowBundle.js:50914:11)
   at reconcileChildFibers (http://localhost:3000/direflowBundle.js:50974:15)
   at reconcileChildren (http://localhost:3000/direflowBundle.js:53410:9)
   at updateHostRoot (http://localhost:3000/direflowBundle.js:53882:9)
   at beginWork (http://localhost:3000/direflowBundle.js:55203:11)
   at callCallback (http://localhost:3000/direflowBundle.js:36875:13)
   at h (https://cdn.jsdelivr.net/npm/@webcomponents/webcomponentsjs@2.4.1/bundles/webcomponents-sd.js:45:392)
```

**Comment by BastianMa** [comment]
i have made a testbuild under ubuntu and copied the direflowBundle.js to windows and it doesnt work either

**Comment by nicocunin** [comment]
Hi,

I investigated the issue. Here is my feedback.

### Issue in production (yarn build)
1) ProxyPolyfill requires the Proxy object to have the attribute on which a getter is defined:
`
return new Proxy<any>(
    { open: null, closed: null }, // -> code added here to define open and closed attributes
    {
      get(_: unknown, mode: 'open' | 'closed') {
        if (componentMap.get(webComponent)) {
          return componentMap.get(webComponent);
        }

        const proxyComponent = createProxyComponent({ webComponent, mode, shadowChildren });
        componentMap.set(webComponent, proxyComponent);
        return proxyComponent;
      },
    },
  );
`

2) Promise polyfill (included in react-polyfill/ie11) seems to be loaded too late, fixed it by changing the webpack config instead of adding imports at the top of the `index.tsx`:
```
webpackConfig.entry = [
    path.join(__dirname, 'node_modules', 'abortcontroller-polyfill/dist/abortcontroller-polyfill-only'),
    path.join(__dirname, 'node_modules', 'proxy-polyfill'),
    path.join(__dirname, 'node_modules', 'react-app-polyfill/ie11'),
    path.join(__dirname, 'node_modules', 'react-app-polyfill/stable'),
    ...webpackConfig.entry];
```
--> You can assign me the ticket is you want I'm going to create a PR on direflow-docs for 1) and a PR on direflow for 2)

### Issue in dev mode:
This is a well known issue with react-dev-utils (and other libs) using ES6 target when built. So they use const and arrow functions which are not supported by IE 11. I'm working to find some fixes or workarounds with webpack in order to transpile these libraries to ES5 but not the others.

**Comment by Silind** [comment]
You're the man, @nicocunin !
I've assigned you to the task. Thanks! You're gonna make a bunch of people really happy :smile:

**Comment by thatzacdavis** [comment]
Yas @nicocunin! Let me know if you need help validating!

**Comment by thatzacdavis** [comment]
I can confirm that proxy change is working perfectly once everything is polyfilled in IE11.

**Comment by nicocunin** [comment]
And doc update here: https://github.com/Silind-Software/direflow-docs/pull/5

**Comment by BastianMa** [comment]
Hi, nice job!
I have still problems with activated shadowDom and get the error

`Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.`

if i add 

```
webpackconfig.entry = [
        path.join(__dirname, 'node_modules', '@webcomponents/webcomponentsjs/webcomponents-bundle.js'),
        path.join(__dirname, 'node_modules', '@webcomponents/webcomponentsjs/custom-elements-es5-adapter.js'),
        path.join(__dirname, 'node_modules', 'abortcontroller-polyfill/dist/abortcontroller-polyfill-only'),
        path.join(__dirname, 'node_modules', 'proxy-polyfill'),
        path.join(__dirname, 'node_modules', 'react-app-polyfill/ie11'),
        path.join(__dirname, 'node_modules', 'react-app-polyfill/stable'),
        ...webpackconfig.entry];
```
i got an stackoverflow-error.

any ideas somebody?

**Comment by nicocunin** [comment]
Hi @BastianMa ,

To fix the `SCRIPT28: Out of stack space` error, move `path.join(__dirname, 'node_modules', '@webcomponents/webcomponentsjs/webcomponents-bundle.js'),` right before `...webpackconfig.entry`. It should then work !

BTW, to add these 2 additionals polyfills (@webcomponents), you could also have followed the direflow-docs with the polyfill-loader plugin [here](https://direflow.io/plugins#polyfill-loader). It depends if you prefer to embed these polyfills in your webcomponent or if you prefer to use a script link in the HEAD of your HTML pointing to a CDN...

**Comment by Silind** [comment]
This fix is now included in v. 3.4.10

**Comment by mfreville** [comment]
Hey, 

I have update my direflow project to 3.4.11 and I think there is one last missing package to add in the documentation for ie 11 support about the custom event polyfill.

IE beat me when I fire event to the main application.

`yarn add custom-event-polyfill`

`// IE 11 polyfills
function configWithIE11(config) {
    config.entry = [
        path.join(__dirname, 'node_modules', 'react-app-polyfill/ie11'),
        path.join(__dirname, 'node_modules', 'react-app-polyfill/stable'),
    + path.join(__dirname, 'node_modules', 'custom-event-polyfill'),
        path.join(__dirname, 'node_modules', 'abortcontroller-polyfill/dist/abortcontroller-polyfill-only'),
        path.join(__dirname, 'node_modules', 'proxy-polyfill'),
        ...config.entry];
    return config;
}`

KR,
MFreville

**Comment by thatzacdavis** [comment]
I had fixed that personally with an if statement to use the IE11 way to dispatch events. I didn't even realize there was a polyfill available for it, thanks for pointing that out!
