### ISSUE TITLE
Property names can be referenced as an attribute using kebab-case

### ISSUE THREAD

**Issue by Silind** [Silind-Software/direflow#126]
## Feature

When using attributes, kebab-case should be automatically recognized.

When I register a property to my Direflow Component:
```javascript
App.defaultProps = {
  componentTitle: "My Component Title"
}
```

I should be able to reference these as an attribute using kebab-case
```html
<web-component component-title="New Title"></web-component>
```

**Comment by Silentscripter** [comment]
I'm ready to handle this, we should define if the camelCase attribute version should be preserved or use only the standard kebab-case conversion. In the latter case this would mean to bump a major release in my opinion as it would break actual component usages.

**Comment by Silind** [comment]
Sounds great! :smile: 
I think we should make a gradual transition and preserve the camelCase attribute for now. Then deprecate it at a later time, so we can "batch" more breaking changes into a major or minor version bump.
But I'll update the docs to reflect that this is now the 'standard' behavior of the Direflow Components.

**Comment by Silentscripter** [comment]
I agree with this strategy, sounds fine.

**Comment by Silind** [comment]
Moving this back to todo, so this one is again up for grabs 😄

**Comment by Silind** [comment]
This feature is considered redundant for the moment.

**Comment by JasonPaape** [comment]
@Silind,

Why is this closed and considered redundant? It seems that if I pass in a prop via an attribute that I need to use all lower case for my prop, for example:

App.defaultProps = {
  componenttitle: "My Component Title"
}

<web-component componenttitle="New Title"></web-component>

So when componenttitle changes, my useEffect in my component gets the change. If my prop is componentTitle and I set the html attribute to componentTitle it reverts to all lowercase (as html is case insensitive), and my component doesn't get the changed value.

I'm using the latest 3.5.0 version. Is there a way for me to use camelCase prop and have it update using an attribute in html?
