### ISSUE TITLE
Support for serialized data via attributes

### ISSUE THREAD

**Issue by Silind** [Silind-Software/direflow#127]
## Feature

Passing data to an attribute as JSON format should be automatically parsed.

```javascript
App.defaultProps = {
  sampleList: ['Sample 1', 'Sample 2', 'Sample 3']
}
```

Now, I should be able to pass in the following data, and the Direflow Component will automatically recognize this as an Array type, and parse the value:

```html
<web-component 
  sampleList="['New item 1', 'New item 2', 'New item 3']"
>

</web-component>
```

**Comment by Silentscripter** [comment]
Hi @Silind , I am ready to work on this issue

**Comment by fabiofranzini** [comment]
Hi, there are update on this issue?

**Comment by Silind** [comment]
Moving this back to todo, so this one is again up for grabs 😄

**Comment by KomalPandya** [comment]
I'm trying to pass JSON object as a prop to the Direflow component. Its able to render it the first time but not picking on changes in props for re-rendering.
Can you please help here?
