### ISSUE TITLE
Main index file not found when running the default setup

### ISSUE THREAD

**Issue by mrnazarod** [Silind-Software/direflow#134]
**Describe the bug**  
Direflow fails to load the main index.js (or .tsx) file when running in the browser.

**To reproduce**  
1. Follow the Get Started step 'Create New Direflow Setup'
2. Open the browser console.
3. See warning 'File is not found: C:pathtoyourdireflowfoldersrcindex.js'
4. Notice that the expected log output from the main index file is missing (e.g., 'my-component is mounted on the DOM').

**Expected behavior**  
The default setup works out of the box.

**Package Manager:**  
To install Direflow, I used npm.

**Screenshots**  
![direflow-index](https://user-images.githubusercontent.com/64977678/81321018-10b85f00-9060-11ea-93f8-015d210e1f6d.png)

**Comment by Silind** [comment]
Hi @mrnazarod 
Thank you for creating this issue.

May I assume that your working on a Windows machine?

**Comment by mrnazarod** [comment]
Yes @Silind, I'm on Windows 10.

**Comment by dvselva** [comment]
Hello, I am also getting the similar error. it runs fine in development mode from IDE. But when i bundle this and include on webpage, i am getting the error 
direflowBundle.js:1 File is not found: C:Userssed9089DesktopSelvaDireflowwebcomp-componentsrcindex.js
