### ISSUE TITLE
Documentation of direflow web component with Docz?

### ISSUE THREAD

**Issue by lioshi** [Silind-Software/direflow#139]
Hi,

I see that direflow.io use Docz.
Is there a meaning to use Docz to document webcomponent created with Direflow like it work with React Components?

**Comment by Silind** [comment]
Hi @lioshi 

Docz is simply a great Gatsby theme to get started writing documentations fast :blush: 
But we don't use any playground capabilities or the like, if that's what you're thinking.
So there is no specific reason that it's Docz, other than it being a cool theme that's easy to use with Gatsby :+1:

**Comment by lioshi** [comment]
Yes thanks. If it can be useful for someone, a webcomponent from direflow in Gatsby/Docz

```jsx
---
name: 'Get started'
route: '/get-started'
edit: false
---

# Get Started

import { Playground } from 'docz'
import { Helmet } from 'react-helmet'

# MyComponent

<Playground>
  <Helmet>
    <script charset="utf-8" src="(...)/direflowBundle.js"></script> 
  </Helmet>
  <my-component></my-component>
</Playground>
```

**Comment by Silind** [comment]
Thanks for the example code :slightly_smiling_face:
