### ISSUE TITLE
Material-UI popover components with rootRef are not styled

### ISSUE THREAD

**Issue by saraivinha85** [Silind-Software/direflow#141]
**Describe the bug**  
The documentation says to use RootRef with popover components.
However, the components are generated without any CSS style.

**To reproduce**  
See the example:
https://github.com/saraivinha85/material-css-bug

**Expected behavior**  
Components are styled

**Comment by Silind** [comment]
Hi @saraivinha85
Thank you for creating this issue and a reproduction example 👍 

@nicocunin, maybe you know what is going on here?

**Comment by saraivinha85** [comment]
@Silind Looks like it's not a direflow issue.
The mui component needs to be controlled. After adding the open props:

open={open}
onClose={handleClose}
onOpen={handleOpen}

The rootRef starts working and the component is styled.

Thanks!

**Comment by Silind** [comment]
Alright, great to hear that 😄 
Thanks for letting us know. I'm closing this issue again 👍
