### ISSUE TITLE
"npm publish" on private repo gitlab?

### ISSUE THREAD

**Issue by lioshi** [Silind-Software/direflow#142]
Hi,
I want to use my private gitlab repo as a NPM point and use it like this:

```bash
npm install gitlab:MyName/myDireflowComponent
```

An idea?

PS: I allready make this "NPM install" with React component Lib repo on gitlab made with https://github.com/transitive-bullshit/create-react-library

**Comment by Silind** [comment]
Hi @lioshi 
I don't think this is Direflow specific - you need to configure your package.json to use your private package registry, just as you would any other project.

Then you can add an entry `"main":"build/direflowBundle.js"` if you want to have this being your entry point of the package 🙂

**Comment by lioshi** [comment]
Ok, thks !
