### ISSUE TITLE
copy index.html file from public folder to build folder

### ISSUE THREAD

**Issue by vijay-kumar-singh** [Silind-Software/direflow#145]
Hi 
I want to run generated web component on server. So while running direflow build script, i want to copy index.html from public folder to build folder so that build folder can to uploaded to any server and server can serve index.html which include compiled js file.

**Comment by Silind** [comment]
Hi @vijay-kumar-singh 
Thank you for creating this issue 🙂 

We'll take this as a feature request and consider it in a feature version 👍

**Comment by charleshimmer** [comment]
I second this, the `build` step does seem to be lacking without support for hosting the exported web component.  If you look at what CRA does for build it gives you everything you need to run the build along with the build (index.html linked to the built JS and CSS).

**Comment by Silind** [comment]
Hi @vijay-kumar-singh and @charleshimmer 
As of v3.5 you can now achieve this by using the `emitIndexHTML` in the direflow-configuration.json file.
You can also use `emitAll` which will emit all files from CRA.

See more here:
https://direflow.io/configuration

**Comment by charleshimmer** [comment]
Ah thanks. I found `emitIndexHTML` did in fact emit the index.html file, but it was linked to CSS files that were not produced. I actually they were but were then deleted. If I use `emitAll` it works like I expected.
