### ISSUE TITLE
[question] How to include fonts from npm package

### ISSUE THREAD

**Issue by hmurt** [Silind-Software/direflow#146]
Hi, and thank you for this great tool.

My problem is that font files are not included in the build.

I have a direflow component where I need to import a style library from npm. In my App.jsx I have:
```
import typography from 'my-style-package/typography.scss';

const App = (props) => {
  return (
    <Styled styles={typography} scoped={false}>
      ...
    </Styled>
  );
};
```
I peeked inside `node_modules/my-style-package/typography.scss` and there are references to font files such as:
```
@font-face {
  font-family: 'Sans Thin Italic';
  src: url('./fonts/Sans-ThinItalic.woff2') format('woff2'), url('./fonts/Sans-ThinItalic.woff') format('woff');
  font-weight: 100;
  font-style: normal;
}
```
In development mode (`npm start`) the fonts are loaded from `http://localhost:3000/static/media/Sans-ThinItalic.55666c19.woff2` and it works well. This is all automatic. But they are not included in the direflowBundle.js that is made by `npm run build`.

The imported npm package includes dozens of fonts and I will be using only a fraction of those. During development, I don't necessarily know which ones are used by my code, but it seems that the development server is not loading the fonts that are not actually referenced anywhere in my component.

What is a good way to include the needed fonts in the direflow component that is built?

**Comment by hmurt** [comment]
I managed to go around this problem by hosting the style library in a separate CDN and including the fonts there. Then I load the css using the Direflow external-loader plugin.

**Comment by Silind** [comment]
Hi @hmurt 
Sorry for the late reply.
Great you figured it out - the `external-loader` plugin was exactly what I'd suggest as well.

I know this is a bit cumbersome - we are looking into a way to handle fonts in a more general way 👍
