### ISSUE TITLE
Using imported css file

### ISSUE THREAD

**Issue by icymaru** [Silind-Software/direflow#150]
I'm using a component library which requires me to import a css file explicitly. Something like this:

```
import 'library/dist/main.css';

const App = () => {
  return <CustomButton>I'm a button</CustomButton>;
}
```

So in order for the CustomButton to work, it needs the css file. Is this possible using direflow?
Btw, very cool framework. Thanks for sharing this! :))

**Comment by Silind** [comment]
Hi @icymaru 

Yes, this is possible, but you need to explicitly pass the styles into the `Styled` wrapper component as described in [our documentation](https://direflow.io/styling) :blush: 

```jsx
import { Styled } from 'direflow-component';
import styles from 'library/dist/main.css';

const App = () => {
  return (
    <Styled styles='styles'>
      <CustomButton>I'm a button</CustomButton>
    </Styled>
  );
}
```

**Comment by icymaru** [comment]
Oh yeah your right and I can set the **scope** to false... :)
Thanks for answering my questions :)
