### ISSUE TITLE
Support Dart Sass

### ISSUE THREAD

**Issue by johnmcase** [Silind-Software/direflow#151]
**Is your feature request related to a problem? Please describe.**  
Currently direflow is compiling sass with lib-sass.  I would like for it to use the new dart sass (npm 'sass' module) so that I can take advantage of the new goodies in there that are not  available in lib-sass (@use and @forward specifically)

**Describe the solution you'd like**  
Either direflow always uses dart sass out of the box or there is a simple way to configure it to do so.

**Describe alternatives you've considered**  
According to the `sass-loader` [documentation ](https://webpack.js.org/loaders/sass-loader/) installing the 'sass' module should make it prefer using dart sass, so I tried installing that in my direflow project but it is still erroring out when trying to compile sass that makes use of @use 

**Additional context**  
I am using styled-components here, not sure if that makes a difference.

**Comment by Silind** [comment]
Hi @johnmcase 
Thank you for creating this issue.

It makes very good sense - that's definitely something that we'll be looking into!

**Comment by johnmcase** [comment]
I did verify that all the cypress tests still pass:

![image](https://user-images.githubusercontent.com/314819/87799409-cba86a00-c812-11ea-9cf0-8b890e470012.png)

**Comment by Silind** [comment]
My apologies for the late response.

Awesome work, @johnmcase!
I verified that everything works as expecting.
Getting this merged in now 😊
