### ISSUE TITLE
VSCode Launch.JSON

### ISSUE THREAD

**Issue by say25** [Silind-Software/direflow#159]
**Is your feature request related to a problem? Please describe.**  
It would be awesome if the direflow CLI provided a `launch.json` to build and debug direflow WebComponents out of the box.

**Describe the solution you'd like**  
Ideally the CLI would provide a `launch.json` configuration that allows launching and debugging + attaching to a direflow project.

**Describe alternatives you've considered**  

**Additional context**  
- https://code.visualstudio.com/docs/editor/debugging

**Comment by say25** [comment]
I got this working with the below `launch.json`. I intentionally have it not open a browser in the `yarn start` step to avoid having two instance going at the same time

```json
{
  // Use IntelliSense to learn about possible attributes.
  // Hover to view descriptions of existing attributes.
  // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
  "version": "0.2.0",
  "configurations": [
    {
      "command": "yarn start:no-browser",
      "name": "Run yarn start",
      "request": "launch",
      "type": "node-terminal",
      "presentation": {
        "hidden": true,
        "group": "",
        "order": 2
      }
    },
    {
      "type": "pwa-chrome",
      "request": "launch",
      "name": "Launch Chrome against localhost",
      "url": "http://localhost:3000",
      "webRoot": "${workspaceFolder}/src",
      "skipFiles": ["${workspaceFolder}/node_modules/"],
      "presentation": {
        "hidden": true,
        "group": "",
        "order": 1
      }
    },
    {
      "type": "pwa-msedge",
      "request": "launch",
      "name": "Launch Edge against localhost",
      "url": "http://localhost:3000",
      "webRoot": "${workspaceFolder}/src",
      "skipFiles": ["${workspaceFolder}/node_modules/"],
      "presentation": {
        "hidden": true,
        "group": "",
        "order": 1
      }
    }
  ],
  "compounds": [
    {
      "name": "Chrome Launch and Debug",
      "configurations": ["Run yarn start", "Launch Chrome against localhost"],
      "stopAll": true
    },
    {
      "name": "Edge Launch and Debug",
      "configurations": ["Run yarn start", "Launch Edge against localhost"],
      "stopAll": true
    }
  ]
}
```

**Comment by Silind** [comment]
Awesome, thanks a lot for the template :smile: 
I'll definitely look into this, it sounds like a great resource!

**Comment by say25** [comment]
I don’t mind opening a PR for it

**Comment by Silind** [comment]
Sorry for the late reply, @say25 
A PR would be awesome :muscle:

**Comment by Silind** [comment]
We're gonna carry on with this feature [here](https://github.com/Silind-Software/direflow/issues/175).
