### ISSUE TITLE
direflow-scripts build return exit code 0 on failure

### ISSUE THREAD

**Issue by onhate** [Silind-Software/direflow#163]
**Describe the bug**  
direflow-scripts are not returning proper exit code on failure, I've noticed that build command for example spawns a child process but does not listens to exit code, for example:

the code now:
```js
function build(args: string[]) {
  spawn('react-app-rewired', ['build', ...args], {
    shell: true,
    stdio: 'inherit',
    env,
  });
}
```

how it should be:
```js
function build(args: string[]) {
  spawn('react-app-rewired', ['build', ...args], {
    shell: true,
    stdio: 'inherit',
    env,
  })
  .on('exit', function(code){
    process.exit(code)
  });
}
```

**To reproduce**  
1. Create a new component with `direflow create` and run `npm install` or `yarn install`
2. Open `App.js` and add a random import for example `import something from 'nowhere';`
3. Build the component running `npm run build` or `yarn build`
4. Run `echo $?` and see it returns exit code 0

```
$ npm run build   

> xxx-component@1.0.0 build /private/tmp/xxx-component
> direflow-scripts build

Creating an optimized production build...
Failed to compile.

./src/direflow-components/xxx-component/App.js
Cannot find module: 'nowhere'. Make sure this package is installed.

You can install this package by running: npm install nowhere.


$ onhate@jamaica xxx-component % echo $?         
0
```

**Expected behavior**  
The exit code from spawn process should be yielded 

**Package Manager:**  
npm or yarn, both fail the same way.

**Comment by onhate** [comment]
I'll raise a PR with suggested changes

**Comment by Silind** [comment]
Awesome, @onhate :raised_hands: 
Nice catch!

We'll review as soon as possible!
