### ISSUE TITLE
Are we able to load custom fonts ?

### ISSUE THREAD

**Issue by mfreville** [Silind-Software/direflow#171]
I have to load custom font into the builded web component bundle.

I already tried to :
- Follow this documentation : https://github.com/typekit/webfontloader#custom (NOK)
- Add the custom fonts through material ui : https://material-ui.com/customization/typography/#self-hosted-fonts (NOK)
- Add the fonts (WebFont with css file containing @Font-Face definition) in the index.html from public folder (OK in local mode)

With these tests I'm able to see the custom font in local mode of my web-component.
It doesn't work when it's builded for production.

I already look for this kind of issue here and I saw that it was needed to use the external loader to load custom fonts from a CDN.
Is there today the only way to load custom fonts in a direflow setup base project ?
It's possible that I missed something too :)

Kind regards,
MF.

**Comment by Silind** [comment]
Hi @mfreville 

Yes, that is correct.
Direflow compiles your bundle into a single js-file, and if you need external files of any kind included, you will need to serve this along with your bundle, and reference them using `external-loader` plugin :blush:

**Comment by mfreville** [comment]
Thanks for your answer :) 
I will follow this way.
