### ISSUE TITLE
Material-UI select menuitem generated outside of web component

### ISSUE THREAD

**Issue by vijay-kumar-singh** [Silind-Software/direflow#187]
**Describe the bug**  
Material-ui select menuitem is being displayed outside of web component. I have updated my code as per tips to use material-ui
https://direflow.io/guides-and-tips#tips-for-material-ui
but still issue is not getting fixed.

**To reproduce**  
1. Install 'add material-ui plugin in Plugins section of index.js'
2. add script to use material-ui select component
3. Build th project
4. See error. select menuitem being populated outside of web component.

**Expected behavior**  
Select Menuitems should display along with component.

**Package Manager:**  
To install Direflow, I used... (npm )

**Screenshots**  
![image](https://user-images.githubusercontent.com/26203635/98119337-c5ff8e80-1eac-11eb-942b-290139d38fc0.png)
.

**Additional context**  
Script :
import RootRef from "@material-ui/core/RootRef";
const domRef = React.createRef();
return (
  <div>
    <RootRef rootRef={domRef}>
      <FormControl>
        <InputLabel>Age</InputLabel>
        <Select style={{ width: 100 }} MenuProps={{ container: domRef.current }}>
          <MenuItem value={10}>Ten</MenuItem>
          <MenuItem value={20}>Twenty</MenuItem>
          <MenuItem value={30}>Thirty</MenuItem>
        </Select>
      </FormControl>
    </RootRef>
  </div>
)

**Comment by Silind** [comment]
Hi @vijay-kumar-singh 
Thanks for creating this issue.

We'll take a look as soon as possible.

**Comment by Stevemoretz** [comment]
https://github.com/Silind-Software/direflow/issues/194#issuecomment-754210213
I believe I found your answer.

**Comment by vijay-kumar-singh** [comment]
I am able to solve issue by referring 
[#194 (comment)](https://github.com/Silind-Software/direflow/issues/194#issuecomment-754210213)

**Comment by Stevemoretz** [comment]
As I mentioned that doesn't work if you have a textfield in the popper.

**Comment by mjbedford** [comment]
Sorry to re open this but I do not see how the resolution mentioned above work to solve this issue , could someone post a sample that show a working select, Thanks
