### ISSUE TITLE
How to publish direflow component as npm package?

### ISSUE THREAD

**Issue by KomalPandya** [Silind-Software/direflow#191]
I have developed a web component in TypeScript using Direflow. While setup, I got a question "Do you want this as an NPM module?" - I had selected "Yes".
Can you tell me how to publish the component as an npm package or how to access the same?

**Comment by Psvensso** [comment]
This is nothing Direflow handles for you, the cli just prepares some handy presets. 
If you create two packages, one with "Npm module: true" and one "Npm module: false" you can see in the package.json that some things are different. 

Main differences is that a "package" that shall be distributed on npm requires a main file. That's added to the package.json and in a "none npm module" the private property is set to true, indicating that is should not be published. (It also adds some meta tags, see in [template](https://github.com/Silind-Software/direflow/blob/e2207d45cfbef6317dffc435dbd13df0ca569322/templates/ts/package.json))

I would read up NPM modules here: 
https://docs.npmjs.com/packages-and-modules/introduction-to-packages-and-modules

But in short, just build and run 'npm publish' and your done.
