### ISSUE TITLE
Shadow option is not available with direflow-component ^1.0.26

### ISSUE THREAD

**Issue by somsharp** [Silind-Software/direflow#20]
Earlier version I was able to pass shadow option like below:
//direflowComponent.render(CcmInvoiceTile, 'sw-ccm-invoice-summary-tile', **{ shadow: false,  }**);

with the new latest version "direflow-component": "^1.0.26" Now it supports only two parameter. Is there a way to pass the shadow option as false?  Some of our existing component does not need shadow feature at all.

**Comment by pedrodgfaria** [comment]
[from last merged pr](https://github.com/Silind-Software/direflow/pull/16/commits/9e86ae21c8e32829d57a976793971c506283b227
)

now you have: 
```
 constructor(option?: { shadow: boolean }) {
    if (option && !option.shadow) {
      this.shadow = false;
    }
  }
```
you can try use: 

`const direflowComponent = new DireflowComponent({shadow: false});
`

**Comment by somsharp** [comment]
Thanks a lot for quick response. It is working as expected.

**Comment by Silind** [comment]
Spot on, @pedrodgfaria. Thanks a bunch :blush: 

I've updated the webpage so the documentation reflects these new changes.
https://direflow.io/additional#shadow-dom
