### ISSUE TITLE
[IE11] Material-UI styles are not isolated between components

### ISSUE THREAD

**Issue by alex-fournier** [Silind-Software/direflow#200]
**Describe the bug**  
In Internet Explorer 11, when having multiple direflow components using material-ui components in the same page, styles are not isolated between components. It leads to a corrupted style.

I think CSS encapsulation in web components has some limitations, especially when using Internet Explorer. We should use a prefix or something to make any CSS class unique and avoid any style corruption.

I will submit a pull request very soon to fix this issue.

**To reproduce**  
1. `git clone https://github.com/alex-fournier/hello-direflow.git`
2. `cd hello-direflow`
3. `yarn install`
4. `yarn start`
5. Open `http://localhost:3000` in IE 11
6. The `Select` mui component in Foo component is broken due to the styles added by `Button` mui component in Bar component.

**Expected behavior**  
Material-UI styles should be encapsulated in shadow dom and should not impact other components.

**Package Manager:**  
To install Direflow, I used yarn

## Expected
![expected](https://user-images.githubusercontent.com/1874622/105977310-80102c00-6091-11eb-85d6-4a67cac92bc7.jpg)

## Actual result in IE11
![actual](https://user-images.githubusercontent.com/1874622/105977337-8900fd80-6091-11eb-88db-7643f1bb813e.jpg)

**Comment by JohnDeved** [comment]
thank you, for your issue submission and contribution!
I will have a look at your PR later today 🙂

**Comment by alex-fournier** [comment]
@JohnDeved Did you have time to take a look at the PR #201 ? This issue is blocking for us :(

**Comment by JohnDeved** [comment]
Yes sorry, kind of got carried away with stuff.
I'll make sure to approve it asap, so that it won't be a blocker for you anymore

**Comment by SimonHoiberg** [comment]
Apologize for the wait.

This is now included in v. 3.5.2 🙌

**Comment by alex-fournier** [comment]
Thanks a lot :)
