### ISSUE TITLE
Synchronizing properties and attributes

### ISSUE THREAD

**Issue by alkismavridis** [Silind-Software/direflow#23]
Hello dear direflow team.
I would like some input parameters to be controlled both via attributes and via properties, like the native html **title** property/attribute works, for example. Attribute and property are **always at sync**.
Of course, the react element should rerender when the property is changed or when setAttribute is called.

If this is to complicated, I would to have at least the one way: the property is set when the attribute changes. 

I have noticed that if I add the "foo" key in both direFlowComponent.setAttributes() and direFlowComponent.setProperties() parameters, only the **property** works. Changing the attribute in the dom will cause no rerendering and will not affect the result of myElement.foo getter.

Do I do anything wrong?
I would really need a configuration that keeps those things at sync, consistently.
Thanks a lot!

**Comment by Silind** [comment]
Hi @alkismavridis 
Thanks for showing interest in Direflow :slightly_smiling_face: 

Your assumptions are correct.
Right now there is a strict separation between _properties_ and _attributes_.
You register your _properties_ and _attributes_ in the `properties` and `attributes` objects in `src/properties.js`, respectively.
These are the only _properties_ and _attributes_ that the React Element will react to.

Your request would definitely be a nice improvement though.

There is a little difference between _properties_ and _attributes_:
With _attributes_ you can only pass in primitive data such as strings, numbers and booleans.
With _properties_ you can pass in both primitive and rich data such as objects and arrays.

Maybe a nice solution would be the following:
- _Attributes_ are always reflected onto _properties_.
  In this case, you would be able to use 'title' both as an _attribute_ and a _property_, if they're registered on the `attributes` object.
- _Properties_ are reflected onto _attributes_ to the extent that it's a primitive data type.
  In that case, you would be able to use 'title' both as an _attribute_ and a _property_, if they're registered on the `properties` object, however 'samplelist' (the array property from the Direflow example code), would not be reflected onto _attributes_, hence doing something like `<webComponent samplelist='something'>` would simply have no effect.
- If a property with the same name is registered on both the `attributes` and `properties` object, a _property_ takes precedence.

What do you think about such a feature?
Does it somewhat capture your needs?

Let me hear if anything is unclear or if I misunderstood something :blush:

**Comment by alkismavridis** [comment]
Hello @Silind 
Thanks for the quick answer!

Yes, you are absolutelly right that the property -> attribute sync can be problematic for non primitive types.

I also believe that the rule of syncing properties to attributes only if they are primitives makes a lot of practical sense.
At the same time, I think that such distinction is to implicit and could make the behavior of the web component confusing because the users of the web component would not realize easily this implicit rule.
My intuitive suggestion would be to avoid the primitive / non primitive distinction in the behavior.

I think the best solution would be, as you mentioned, that changes in attributes always set the property, but not the other way around.

As I see now, this is exactly what vuejs webcomponent compilation and sveltejs compilation do, by default at least.

So, my suggestion would be to make the attribute -> property sync the default behaviour of direflow. Additionally and when you find time, you could also provide a configuration option to override this default behavior. Examples of such overriding that could involve a callback function that does the custom magic, or maybe an enumeration with pre-specified sync policies.
But I think that at the moment, the attribute -> property sync is a very legit choice.

An other thing that would be **awesome** would be to auto-detect and auto-configure the properties.
I am not sure how this could work, but I notice that for example vue automatically includes all "props" of the component as "propertes". Similarly, Svelte automatically includes all variables marked with the export keyword.
This gives the user the feeling that everything works out of the box, without the need of extra manual configuration, or double work when we need to add/remove props. It would be **really great** to have such auto prop-detection in direflow in some form.

It would also bind nicely with the auto sync feature, because it would completely remove the need to manually configure attributes/props. By default at least: the configurations would be still there for any specialized use case. This would make the react -> web component conversion much simpler.

The user would just register the component and everything would work out of the box.

Sorry for the huge message. I hope I did not get off topic.
Best Regards,
Alkis

**Comment by Silind** [comment]
I think the long message is awesome, cause you have many very nice suggestions, and good points :muscle: 

I think you are right, that a good first step would be to let attributes reflect on properties.
Later on, we'll try to look into a way of providing some automatic (and intuitive behavior) for all this, with the ability to customize.

Again, great suggestions!
I'll include this issue as a task for creating this first step, so you can keep it open :blush: 

Cheers!

**Comment by Silind** [comment]
New release of Direflow (2.1.x) now addresses parts of this issue.

The folder structure has changed so that the `properties.js` file is now left out.  
[See more here](https://direflow.io/get-started#the-setup)
  
Properties are now set directly in the `index.js` file where the Direflow Component gets mounted, and will be representing both properties and attributes so that they can be used both places and are 'in sync'  
Only primitive values will be accessible through attributes.  
[See more here](https://direflow.io/properties#reflection-of-properties)
  
The additional suggestions in the issue will be addressed sometime later on :slightly_smiling_face:

**Comment by alkismavridis** [comment]
Thanks you very much, @Silind !
I really believe that combining react and web-components is a really important good cause.
I think I could contribute, if you want me to, of course, in the project.

I would love to make a first attempt to implement the automatic-props detection, or something that goes in that direction.
I might have some time in the next days for that.

Would you like me to try something out?
If yes, which workflow would you prefer:
Allowing me a branch in the repo, or having me forking the repo work in my copy? Or somehing else?

Please do not hesitate to contact me at alkismavridis@gmail.com

Best Regards!

**Comment by Silind** [comment]
You are very welcome to contribute by giving the implementing of a automatic-props detection feature a shot - that would be awesome!
I think there could be some challenges on the way, and a trade-off will probably have to be, that you will still have to manually update the `IProps` interface in App.tsx and the `PropTypes` in App.js.
But that part is optional anyway, so that's a totally fair tradeoff.

Please go ahead and fork the repository, and refer to the [Contribution Guide](https://github.com/Silind-Software/direflow/blob/master/CONTRIBUTING.md#pull-request) to see how to quickly get started with developing on Direflow :smiley: 

Cheers man, really appreciate the interest and that you want to take a look at this :blush:
