### ISSUE TITLE
Can't Go Offline

### ISSUE THREAD

**Issue by YehudaKremer** [Silind-Software/direflow#230]
Hello there

Im trying to get my web component work 'offline' with no externals dependencies,
i followed the instructions in the [Offline support](https://direflow.io/additional#offline-support) guide,
and polyfills are now include in the bundle, but the React libs are not include in the bundle and i getting always externals:
- https://unpkg.com/react@16/umd/react.production.min.js
- https://unpkg.com/react-dom@16/umd/react-dom.production.min.js

**To reproduce**  
1. direflow-webpack.js: 
![image](https://user-images.githubusercontent.com/946652/118165075-8baf1500-b42c-11eb-9376-34b2392eb54c.png)
2. index.tsx:
![image](https://user-images.githubusercontent.com/946652/118165313-d335a100-b42c-11eb-95a1-24776c09f49f.png)
Results:
![image](https://user-images.githubusercontent.com/946652/118165431-f3fdf680-b42c-11eb-8ee4-8eca0118cec3.png)

**Expected behavior**  
no external dependencies.

**Package Manager:**  
I used yarn, Direflow version:
![image](https://user-images.githubusercontent.com/946652/118166012-a59d2780-b42d-11eb-97ae-2e6d19a5bf86.png)

Appreciate any help, Thank You 👍

**Comment by brentonr94** [comment]
I'm also having the exact same problem, would love to see a solution to this one! Means I'm having to add exceptions into our content security policy in our 'shell' application which is less than ideal.

**Comment by brentonr94** [comment]
> I'm also having the exact same problem, would love to see a solution to this one! Means I'm having to add exceptions into our content security policy in our 'shell' application which is less than ideal.

Have just been doing some trial and error - It looks like i've been able to go completely offline by adding the following to my direflow-config.json file (I had it in the webpack config previously)

`  "modules": {
        "react": false,
        "reactDOM": false
  }
`
