### ISSUE TITLE
Reusing components to create a web component

### ISSUE THREAD

**Issue by subharb** [Silind-Software/direflow#24]
**Is your feature request related to a problem? Please describe.**
What I need is to export a component within my project as a webcomponent. Therefore what I did was to create a subfolder within my project where direflow sits.
When I try to import my component into the App.js of my newly created folder of direflow, I get an error  "Module not found: You attempted to import ../../../src/containers/event/index which falls outside of the project src/ directory. Relative imports outside of src/ are not supported."

**Describe the solution you'd like**
Is there a way/configuration where direflow can import my components from my project.

**Describe alternatives you've considered**

**Additional context**
That's the folder structure of my project, and "widget-component" is the name of the project created with direflow.
![image](https://user-images.githubusercontent.com/3383058/71510384-05be1880-288f-11ea-8e52-23f83b4c7169.png)

**Comment by Silind** [comment]
Hi @subharb 
Thank you for creating this issue.

This constraint has its origin in _create-react-app_, which is the "engine" underneath the Direflow Component.

It is definitely a problem - I will look into a fix for this issue as soon as possible.

**Comment by Silind** [comment]
This issue has been fixed in **v. 2.2.3** :+1:
