### ISSUE TITLE
Question: how pass value with events?

### ISSUE THREAD

**Issue by lucasinocente** [Silind-Software/direflow#25]
Hi! First of all, thanks for sharing this project. Its awesome!

Please, how can I pass value with events? For exemple I wanna pass user:

In web-component: 
```
const handleClick = () => {
    const user = { username: 'lorem' };
    const event = new Event('my-event'); // I pass user here?
    dispatch(event); // Or I pass user here?
  };
```

In the page who are loading the web-component:
```
const component = document.querySelector('component-direflow');
component.addEventListener('my-event', (value) => {
  console.log('value:', value);
});
```

**Comment by lucasinocente** [comment]
Updating:

I use like this:
```
const handleClick = () => {
   const event = new Event('my-event');
   event.value = 123
   dispatch(event);
};
```

and receive with:

```
const component = document.querySelector('component-direflow');
component.addEventListener('my-event', (event) => {
  console.log(event.value); // 123
});
```

And works. But, is this the best way to do this?

**Comment by Silind** [comment]
Hi, @lucasinocente  
Thanks for showing interest in Direflow :slightly_smiling_face: 

The way you are doing it is legit - however, if you were to use TypeScript, the compiler would complain.
I think the most "best practice" way to do it, is to use `CustomEvent`, which carries a `detail` property. This can be used to carry your payload.

Here is an example:

```javascript
const handleClick = () => {
   // Create a custom event with a detail
   const event = new CustomEvent('my-event', {
      detail: {
         value: 123
      }
   });

   // Dispatch the event
   dispatch(event);
};
```

```javascript
const component = document.querySelector('component-direflow');
component.addEventListener('my-event', (event) => {
   console.log(event.detail.value); // 123
});
```

You can read more about it here:
https://developer.mozilla.org/en-US/docs/Web/API/CustomEvent/CustomEvent

**Comment by lucasinocente** [comment]
Thanks @Silind, you help me a lot!
