### ISSUE TITLE
Providing html content using named slots does not work.

### ISSUE THREAD

**Issue by alkismavridis** [Silind-Software/direflow#26]
**Describe the bug**
Providing html content using named slots does not work.

**To Reproduce**
1. Create a simple web component with direflow (using shadow dom).
Include some named slots.
Example:
```
<Styled styles={styles}>
     <div>
      <section id="title">
    		<div>React</div>
    		<slot name="subtitle">subtitle slot</slot>
    	</section>
    	<section id="main">
    		<div>JS dependencies: <b>None</b></div>
    		<div>Minified Size: <b>283.3 Kb</b></div>
    		<div>Shadow dom: <b>Yes</b></div>
        <div>uses native observableAttributes: <b>Yes</b></div>
        <div>can use slots: <b>Yes</b></div>
        <br/>

    		<div>msg is <b>{props.msg}</b></div>
    		{props.msg == 'surprize' &&
    			<div>An extra surprize div.</div>
    		}
    		{props.someList &&
    			<div>someList has {props.someList.length} elements</div>
    		}
    	</section>
    	<section id="footer" onClick={() => clicked(props)}>
    		<slot name="footer">footer slot</slot>
    	</section>
    </div>
  </Styled>
```

2. Use your web component in a html page (I used a plain vanilla html page):
```
<custom-react-element>
    <div slot="subtitle">Custom subtitle</div>
    <div slot="footer">Custom footer</div>
</custom-react-element>
```

**Expected behavior**
The given divs appear inside the web component.

**Actual behavior**
The diven divs appead outside the web component.

**Package Manager (please place an 'x' below):**
To install Direflow, I used...
- [x] NPM
- [ ] Yarn

**Screenshots**
The direflow element is the last one with title "react". 
![image](https://user-images.githubusercontent.com/3485572/71546038-a21d1380-2992-11ea-94aa-03861881bf6f.png)

**Additional context**
Spec: https://developer.mozilla.org/en-US/docs/Web/Web_Components/Using_templates_and_slots

I think that the problem is that direflow **creates a span inside the web component** and attaches the shadow dom on the span.

The user app has no way to know (or influence) this, and inserts the named slot elements parallel to the generated span, not inside it.
Thus the light dom and shadow dom are not merged properly by the browser.

**Comment by Silind** [comment]
Hi @alkismavridis 
Thank you for creating a well-reported issue :+1: 

This is indeed a bug.
The slotted functionality is based on portals and requires the slotted element to be a sibling to the shadow-root.
If you inspect the DOM in devtools and drag the slotted element inside the span tag, text to the shadow-root, you will see it working.

Nice spotted! I will make sure this error is fixed as soon as possible.

**Comment by Silind** [comment]
This issue is fixed in **v. 2.2.0**.
