### ISSUE TITLE
.sass file support

### ISSUE THREAD

**Issue by JohnDeved** [Silind-Software/direflow#37]
**Is your feature request related to a problem? Please describe.**  
Direflow already supports Sass, but only supports the .scss file syntax.
it would be great if .sass files would work as well 

**Describe the solution you'd like**  
expand direflow webpack into supporting .sass alongside .scss files

**Additional context**  
https://sass-lang.com/documentation/syntax#the-indented-syntax

**Comment by Silind** [comment]
Thanks for creating the ussie, @JohnDeved.
It's a good suggestion - I've added this to the todo-list :+1:

**Comment by JohnDeved** [comment]
this is what happens if your try to use a .sass file right now
![image](https://user-images.githubusercontent.com/24187269/72606316-af3c7b00-391e-11ea-88e7-94568cbe9aeb.png)
![image](https://user-images.githubusercontent.com/24187269/72606365-c3807800-391e-11ea-89ca-806975c4dc71.png)

**Comment by Silind** [comment]
Yes, Direflow is currently built on _react-scripts_ from _create-react-app_, and the webpack config doesn't include a loader for `.sass` files.
The loader needs to be manually added to the webpack config.
This can also be done on the individual project in the `direflow-webpack.js` file.

But I do agree that this would be a nice support to have, so I think it should be added in the webpack config that ships with Direflow.

**Comment by JohnDeved** [comment]
thanks,
I've already made a fix for it, I will make a PR when I get home.

**Comment by JohnDeved** [comment]
> and the webpack config doesn't include a loader for .sass files.
No sass-loader already exists in the webpack which works

**Comment by Silind** [comment]
> No, sass-loader already exists in the webpack which works for .scss and .sass files. It's a bug that causes sass to compile wrong

Oh yeah, I see that you're right.

Thanks a lot for the fix!
I'm gonna assign you to this issue, even that you already fixed it.
It's easier to see later who fixed what :blush:
