### ISSUE TITLE
Support for child elements

### ISSUE THREAD

**Issue by Silind** [Silind-Software/direflow#4]
Be able to pass in a child to the Web Component and inject it at a place of choice.

```html
<cool-component>
  <div>
    <span>This is a child</div>
  </div>
</cool-component>
```

We would use a special component in React, and the child should be injected into here.

```jsx
return (
  <Styled styles={styles}>
    <div className='app'>
      <DireflowChild />
    </div>
  </Styled>
);
```

**Comment by Silind** [comment]
Will not be worked on.
For now, similar default behavior is accepted as explained here:
https://developer.mozilla.org/en-US/docs/Web/Web_Components/Using_templates_and_slots

**Comment by krzochalski** [comment]
Is there any example on how to do it?

**Comment by johnmcase** [comment]
Is there any way to implement this when the component has `useShadow` set to false?
