### ISSUE TITLE
Implement ESLint in JS template & Make user choose between ESLint and TSLint for TS template

### ISSUE THREAD

**Issue by JohnDeved** [Silind-Software/direflow#40]
**Is your feature request related to a problem? Please describe.**  
Implement ESLint in JS template & Make user choose between ESLint and TSLint for TS template

**Describe the solution you'd like**  
When creating a direflow project, it would be nice to have ESLint setup for the JS template,
just like how TSLint is set up for the TS template already.
And for the TS template, it would be nice if you could choose between TSLint and ESLint.

**Additional context**  
Why ESLint for TypeScript? https://github.com/palantir/tslint/issues/4534

**Comment by JohnDeved** [comment]
Im willing to take care of this if you want

**Comment by Silind** [comment]
@JohnDeved You are very welcome to handle this task :blush: 
I'm gonna assign you to it. Let me know if any questions or uncertainties arise.
