### ISSUE TITLE
Styled wrapper component causing snapshot tests to crash

### ISSUE THREAD

**Issue by Silind** [Silind-Software/direflow#41]
**Describe the bug**  
When running snapshot tests of a React component that includes the `<Styled>` HOC from `direflow-component`, tests crash.
Remove the `<Styled>` from the component, and snapshots are written just fine.

**To reproduce**  
1. Create a new Direflow Setup using `direflow-cli`
2. Install all dependencies and run `yarn test`

**Expected behavior**  
Snapshot tests should be written without jest crashing.

**Screenshots**  
![](https://drive.google.com/uc?export=view&id=1X_ZmAGOV6QoH_iIxNtSndd0yzQYkx3e5)

**Comment by yananym** [comment]
Yep we are facing this is `3.4.9`

**Comment by Silind** [comment]
A temporary fix for this is to globally mock out the direflow-components module before running tests.
```
jest.mock('direflow-component', () => ({
  Styled: props => {
    return props.children;
  },
  EventContext: {}
}));
```

**Comment by Silind** [comment]
This has been fixed in v. 3.4.11.

**Comment by nicocunin** [comment]
Hi Silind,
Can you confirm this version 3.4.12 is not released yet?
The direflow-jest.config.js was not exported during `npm publish` as it's not part of the `files` section in package.json, that's the issue for the 3.4.11 I guess, no?

**Comment by Silind** [comment]
Hi @nicocunin 
Yes, you are correct! That was an unfortunate mistake on my behalf.
I've unpublished 3.4.11, so 3.4.12 is the newest one, including the `direflow-jest.config.js` file :+1: 

3.4.12 is released, it got released yesterday.
