### ISSUE TITLE
Develop multiple web components in the same time

### ISSUE THREAD

**Issue by ussuritiger** [Silind-Software/direflow#42]
**Is your feature request related to a problem? Please describe.**  
I would like to be able to develop multiple web components bundled separately.

**Describe the solution you'd like**  
Having setup where `src` directory can contain multiple folders for every single web component with the `index.js` as an entry point inside every folder (similar as it is for a single web component at the moment).

**Additional context**  
This way I will be able to include all web components in `public/index.html` and develop them simultaneously as well as make a production build for all of them.

**Comment by Silind** [comment]
Hi @ussuritiger 
Thank you for creating a feature request.

I want to make sure I understand your explanation correctly.

If you want to structure your code such that each component has its own index.js file where the Direflow Component is created and properties are set, etc, there is nothing that prevents you from that.
You just need to make sure that this is imported into the main index.js fil.

For instance if you have a `src/my-component/index.js`:
```javascript
export const initMyComponent = () => {
   const myComponent = new DireflowComponent();
   myComponent.configure({ name: 'my-component', useShadow: true });

   // whatever else you need to do to prepare the component

   myComponent.create(App);
}
```

And then in `src/index.js`:
```javascript
import { initMyComponent } from './my-component/';

initMyComponent();
// and here you can call 'init' functions for all other components you have
// initAnotherComponent();
// initAThirdComponent();
// ...etc
```

In this way you can still use them all in the index.html file, and bundle them all together into a production build.

Or do I misunderstand your point here? 😊

**Comment by ussuritiger** [comment]
Thanks for the explanation. What I mean is to be able to develop multiple web components in the same time (perhaps the way that you described about) but still be able to do production build for every single (or multiple) web component.

This way if somewhere I need only a button web component for example, I will only include the bundle file with only button web component. If multiple web components needed (let's say header and footer), I only include bundle file for those two web components. However in development mode it would be nice to work on all of them together.

That's the idea situation. Would be nice if somehow this can be achieved with Direflow.

**Comment by pedrodgfaria** [comment]
You are describing the deprecated [direflow-project](https://www.npmjs.com/package/direflow-project) cli in v2

**Comment by ussuritiger** [comment]
Good to know but I am still wondering if behavior that I've described is achievable with the current version of Direflow or is there any plans/interest in making this possible? Thanks.

**Comment by Silind** [comment]
As @pedrodgfaria mentions, there was a setup similar to what you describe in an earlier version.
It was deprecated due to lack of flexibility. Bundle size was enormous and the setup was quite clumsy and annoying to work with.

However, the answer is somewhat yes; there is a plan for creating the ability to create different bundles thus choosing which separate Direflow Components to be included in a given bundle.
But still have the whole thing in one project during development.

I'll keep this issue open as a reference, and link it when there is more clear idea about the scope of this feature.

**Comment by Silind** [comment]
We have an issue for this [here](https://github.com/Silind-Software/direflow/issues/53).
This feature is planned to be included in the next major release.
