### ISSUE TITLE
Cannot rename build file from webpack override

### ISSUE THREAD

**Issue by lioshi** [Silind-Software/direflow#46]
I want to rename build file: **direflowBundle.js**.
Like this I have error: __ENOENT: no such file or directory, open '/home/lioshi/gitlibs/booki/eilep-booki/build/customeName.js'__

```js
const webpackConfig = require('direflow-component/config-overrides');

/**
 * Webpack configuration for Direflow Component
 * Additional webpack plugins / overrides can be provided here
 */
module.exports = (config, env) => ({
  ...webpackConfig(config, env),
  output: customOutput(config.output)


});

const customOutput = (output) => {
  const { checkFilename, ...newOutput } = output;

  return {
    ...newOutput,
    filename: 'customeName.js',
    chunkFilename: 'vendor.js',
  };
};
```

**Comment by JohnDeved** [comment]
this should work with
```js
module.exports = (config, env) => {
  const cfg = webpackConfig(config, env)
  console.log(cfg.plugins)
  return {
    ...cfg,
    // Add your own webpack config here (optional)
    output : {
      ...cfg.output,
      filename: 'myBundle.js'
    }
  }
}
```
but seems to be blocked by
https://github.com/Silind-Software/direflow/blob/bbe46ce7eba9b7c3f5982fecb405f6deb64843ee/packages/direflow-component/src/config/config-overrides.ts#L131

**Comment by JohnDeved** [comment]
@lioshi 
quick dirty workarround for now
```js
module.exports = (config, env) => {
  const cfg = webpackConfig(config, env)
  cfg.plugins.splice(-2, 1) // workarround
  console.log(cfg.plugins)
  return {
    ...cfg,
    // Add your own webpack config here (optional)
    output : {
      ...cfg.output,
      filename: 'myBundle.js'
    }
  }
}
```

downside is that this will leave some trash files that would have been deleted otherwise in the build folder. but at least it works now

**Comment by Silind** [comment]
Hi @lioshi 
Renaming the bundle is - unfortunately - one of the few things that you cannot just change due to the reasons that @JohnDeved mentions.

The config override is currently cleaning up the build folder for you, and this part is hardcoded.
I'll rename this issue and put it in the project backlog since this is actually something that needs to be adressed :+1: 

Thanks for creating this issue.

**Comment by lioshi** [comment]
> Hi @lioshi
> Renaming the bundle is - unfortunately - one of the few things that you cannot just change due to the reasons that @JohnDeved mentions.
> 
> The config override is currently cleaning up the build folder for you, and this part is hardcoded.
> I'll rename this issue and put it in the project backlog since this is actually something that needs to be adressed 
> 
> Thanks for creating this issue.

Thanks to U for 3.2.1 version ;-)
