### ISSUE TITLE
Setup integration test with cypress

### ISSUE THREAD

**Issue by Silind** [Silind-Software/direflow#48]
Create a new Web Component and render it with puppeteer.
Make assertions on the following criteria:
- Renders with an initial state (initial properties)
- Updates correctly on change attribute
- Updates correctly on change property
- Renders with a slotted element
- Updates when a slotted element is injected dynamically

Integrate with GitHub Actions as a part of the test pipeline.

**Comment by JohnDeved** [comment]
could recommend cypress.io for this as well
