### ISSUE TITLE
Bundle polyfill as splitchunk instead of remote script

### ISSUE THREAD

**Issue by kaiekaie** [Silind-Software/direflow#49]
It would be nice to bundle the polyfill components so you could serve it from your own server with the 
direwolf component after build.

**Comment by Silind** [comment]
Hi @kaiekaie 
Thanks for showing interest in Direflow :slightly_smiling_face: 

This is technically already possible.
You can use the 'polyfill-loader' plugin to specify the address of your polyfill bundles.
You can see how to do that [here in the documentation](https://direflow.io/plugins#polyfill-loader).

Now you simply serve your polyfills and reference the address in the plugin, and the Direflow Component will automatically lazyload the polyfills from there :blush: 

Was that what you were looking for, or do I not understand you correctly?

**Comment by kaiekaie** [comment]
Okei i understand, i will try that out! Thanks!

ons. 22. jan. 2020 kl. 18:42 skrev Simon LH <notifications@github.com>:

**Comment by Silind** [comment]
Great :blush: 
Let me know if you have any problems.

**Comment by kaiekaie** [comment]
Could it be a option to load custom-elements-es5-adapter.js too?
