### ISSUE TITLE
Script-Loader plugins seems to be not working

### ISSUE THREAD

**Issue by mperazac** [Silind-Software/direflow#6]
Hi! This project is great! Thanks for coding it!

It looks like the script-loader is not working.
I added the jquery example from the documentation, but I do not see to be loading anything.

This is my plugins configuration in the direflow-config.js:

```
plugins: [
    {
      name: 'script-loader',
      options: {
        externals: [
          {
            module: 'jquery',
            entry: 'https://unpkg.com/jquery@3.2.1/dist/jquery.min.js',
            global: 'jQuery',
          },
          {
            module: 'bootstrap',
            entry: 'https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css',
          }
        ],
      },
    },
    {
      name: 'font-loader',
      options: {
        google: {
          families: ['PT Sans', 'Noto Sans JP'],
        },
      },
    },
    {
      name: 'styled-components',
    },
  ],
```

Can you please give it a try?

**Comment by Silind** [comment]
Hi @mperazac 

Thank you for creating this issue.

It seems like you're using the script-loader plugin exactly as intended.
I will look into this asap.

**Comment by Silind** [comment]
This issue has been resolved.
The `script-loader` plugin has now changed to `external-loader` and is simplified quite a bit.
In order to achieve the above, you simply do:

```
plugins: [
    {
      name: 'external-loader',
      options: {
        paths: [
          'https://unpkg.com/jquery@3.2.1/dist/jquery.min.js'
          'https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css'
        ],
      }
    },
    {
      name: 'font-loader',
      options: {
        google: {
          families: ['PT Sans', 'Noto Sans JP'],
        },
      },
    },
    {
      name: 'styled-components',
    },
  ],
```

I included this example as a reference, and can also be seen in the docs:
https://direflow.io/plugins#external-loader

**Comment by mperazac** [comment]
Thank you for looking at it.
