### ISSUE TITLE
Material-ui not working 

### ISSUE THREAD

**Issue by ScottBreyer96** [Silind-Software/direflow#63]
**Describe the bug**  
Hello
I want to use a data table based on material-ui.
It works very well when the Shadom Dom is not activated but does not work when it is activated. The style is not applied.

**To reproduce**  

npm install mui-datatables --save
npm install @material-ui/core

The code in my app.js : 

`
import React from 'react';
import PropTypes from 'prop-types';
import { Styled } from 'direflow-component';
import MUIDataTable from "mui-datatables";
import Typography from '@material-ui/core/Typography';
import Box from '@material-ui/core/Box';
import styles from './App.css';

function TabPanel(props) {
  const { children, value, index, ...other } = props;
  return (
    <Typography
      component="div"
      role="tabpanel"
      hidden={value !== index}
      id={`simple-tabpanel-${index}`}
      aria-labelledby={`simple-tab-${index}`}
      {...other}
    >
      {value === index && <Box p={3}>{children}</Box>}
    </Typography>
  );
}

TabPanel.propTypes = {
  children: PropTypes.node,
  index: PropTypes.any.isRequired,
  value: PropTypes.any.isRequired,
};

const App = () => {
  const columns = ["Name", "Title", "Location"];
  const data = [
    ["Gabby George", "Business Analyst", "Minneapolis"],
    ["Aiden Lloyd", "Business Consultant", "Dallas"],
    ["Jaden Collins", "Attorney", "Santa Ana"],
    ["Franky Rees", "Business Analyst", "St. Petersburg"],
    ["Gabby George", "Business Analyst", "Minneapolis"],
    ["Aiden Lloyd", "Business Consultant", "Dallas"],
    ["Jaden Collins", "Attorney", "Santa Ana"],
    ["Gabby George", "Business Analyst", "Minneapolis"],
    ["Aiden Lloyd", "Business Consultant", "Dallas"],
    ["Jaden Collins", "Attorney", "Santa Ana"],
    ["Franky Rees", "Business Analyst", "St. Petersburg"],
    ["Franky Rees", "Business Analyst", "St. Petersburg"],
    ["Aaren Rose", null, "Toledo"]
  ];
  const options = {
    filter: true,
    filterType: 'dropdown',
    responsive: 'stacked',
  };
  return (
    <Styled styles={styles}>
      <div>
      <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" />
      <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons" />
      <link rel="stylesheet" href="https://data.jsdelivr.com/v1/package/npm/mui-data-table/badge" />
      <link rel="stylesheet" href="https://www.jsdelivr.com/package/npm/mui-data-table" />
        <MUIDataTable title={"ACME Employee list"} data={data} columns={columns} options={options} />
      </div>
    </Styled>
  );
};

App.propTypes = {
  sampleList: PropTypes.array,
  componentTitle: PropTypes.string,
};

export default App;`

**Expected behavior**  

Get this when the Shadow DOM is active : 

![Capture d’écran 2020-02-03 à 14 27 04](https://user-images.githubusercontent.com/39304258/73657365-6f052880-4692-11ea-8d8d-3fe87d42447a.png)

......... and not this : 

![Capture d’écran 2020-02-03 à 14 26 41](https://user-images.githubusercontent.com/39304258/73657396-80e6cb80-4692-11ea-806a-56d8541217fa.png)

**Package Manager:**  
NPM

**Additional context**  
Thanks for your great tools

**Comment by JohnDeved** [comment]
thank you @ScottBreyer96 for submitting a bug.
this issue is already tracked in #59, so I will close this issue in favour of that one. 
If there is anything else we can help you with, don't hesitate to let us know :)
