### ISSUE TITLE
How to generate sourcemaps

### ISSUE THREAD

**Issue by chrissena** [Silind-Software/direflow#67]
I'm struggling to work out how to build with sourcemaps?

**Comment by Silind** [comment]
Hi @chrissena 

Currently, the build process only outputs one or two files.
A bundle-file, or optionally and bundle and a vendor-file.
That means that sourcemap-files are stripped during the build-process.

But if I may ask, what is your situation?
Why do you need to produce sourcemaps as a part of the build?

**Comment by chrissena** [comment]
Thanks for the response @Silind 

I see. 

> But if I may ask, what is your situation?

Well, I use sourcemaps for a couple of reasons:

I am building a react app as a web component and using this within a  much larger application in production.

> Why do you need to produce sourcemaps as a part of the build?

The build process of the larger application submits source maps to Sentry.io for error reporting. So exact commits and line numbers can be tracked and associated with runtime errors. This has proven incredibly powerful in quickly fixing bugs. 
Having the react web components also have the source maps available would include them in this very useful tool.

It also allows for general run time debugging using chrome devtools which is very useful during development.

Sourcemaps would be soo useful. It's actually a problem for our solution not having them. Any ideas for a workaround?

**Comment by Silind** [comment]
Ahh, I see.
Well, sourcemaps are still a part of the dev environment.
That means, when you start the setup running `yarn start`, sourcemap for debugging is now included.
They're simply stripped at build time.

There's a couple of solutions, yes.
The easiest one is to just use the bundle as its served during development.
So if you start up using `yarn start`, you can now include your bundle somewhere else from `http://localhost:3000/direflowBundle.js`. Now, sourcemaps are included.

Alternatively, you can bypass the part that strips the sourcemap (and other files) from build.
Take a look at [this reply](https://github.com/Silind-Software/direflow/issues/46#issuecomment-576817759) to another issue.

But actually, let's keep this issue open.
I see that this is a feature that we would like to support in the future.

**Comment by JohnDeved** [comment]
Let's also keep this in mind for #54
