### ISSUE TITLE
"withStyles" is not exposed

### ISSUE THREAD

**Issue by mperazac** [Silind-Software/direflow#7]
Hi,

I tried to use `withStyles` in one component, but seems that it is not exposed in the `direflow-component`

You would also want to update the documentation in https://direflow.io/events-and-styles#styles in order to reflect `direflow-component` instead of `create-react-web-component`

**Comment by Silind** [comment]
Hi @mperazac 

Thank you for creating this issue.

I will look into asap.
-And thanks for pointing out the error on the webpage. That should obviously be changed :slightly_smiling_face:

**Comment by Silind** [comment]
This has been fixed :slightly_smiling_face: 
If you use the version 1.0.17, `withStyles` will be exposed correctly.

Thank you again for bringing this to my attention :+1:

**Comment by mperazac** [comment]
This is great! Thank you!
