### ISSUE TITLE
IE 11 compatibilty issue - No rendering app

### ISSUE THREAD

**Issue by mfreville** [Silind-Software/direflow#76]
Hi dears !

I have some issues in order to launch the app through IE 11

- Bug description
My app has no rendering on IE 11 even after follow the documentation to add polyfills.

- How to
1. Install the latest direflow cli
2. Create a new app using direflow create (JavaScript)
3. Add the polyfills following the documentation
4. Add IE 11 to browserlist in package.json
5. Start the app on IE 11

Remark : I'm using yarn

- Result 
The app doesn't rendering.
Error through the IE 11 console : 
1. Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
2. SCRIPT5022: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
direflowBundle.js (59518,21) 

- After some search
I look for some related issues and I found this :
https://github.com/facebook/create-react-app/issues/8197
It seems there is a react-scripts issue in order to transform arrow functions for IE 11 but they said to use the react-scripts 3.2.0 (the default version embedded in the direflow package.json.

I tried with other react-scripts versions (3.0.0 and 3.0.4) without success.

I do another test using npm install and npm audit fix before start the application and I get this error : 
SCRIPT1002: Erreur de syntaxe
direflowBundle.js (1142,34)

PS : I find difference in your direflow.io documentation about import direflow
```js
// Your documentation
import DireflowComponent from 'direflow-component';

// The generated project with direflow
import { DireflowComponent } from 'direflow-component';
```

**Comment by Silind** [comment]
Hi @mfreville 

Thank you for creating this issue.
It seems very likely that it is a problem with react-scripts from create-react-app.
We will take a look.

Thanks for pointing out the mistake in the documentation.
We will make sure to correct this 👍

**Comment by mfreville** [comment]
Hi @Silind,

I have just test the new version of the direflow-cli.

There is always the same issue on IE 11.

And there is a new error on the build of the component which generate this error :
Error: Polyfill failed to load at HTMLScriptElement.<anonymous>

Do you prefer I create a new issue or this one can be re open ?

I can try to investigate on it later.

Kind regards,
MF

**Comment by Silind** [comment]
Hi @mfreville 
Just to clarify - the error `Error: Polyfill failed to load at HTMLScriptElement.`, is only showing while using IE11, right?
