### ISSUE TITLE
Exposing Methods

### ISSUE THREAD

**Issue by pedrodgfaria** [Silind-Software/direflow#8]
Hi, is it possible to expose methods?

to be called like:
`component.someMethod()
`

**Comment by Silind** [comment]
Hi @pedrodgfaria 
Thank you for showing interest in Direflow.

Yes, that is possible.
If you go to `componentProperties.js` (or `.ts` if you're using TypeScript), you can add a public method as a property:
```javascript
export const componentProperties = {
  someMethod: () => {
    console.log('Do something ...');
  }
};
```
Now you can call it just like you suggest:
```javascript
const component = document.querySelector('my-component');
component.someMethod(); // Do something ...
```
---
Just beware that properties are also reflected as `props`, so when you expose a method like this, you will also get access to this method via `props` in the React app underneath.
Additionally, props have both getters and setters, so you can reassign this method when you consume the component as well:
```javascript
const component = document.querySelector('my-component');
component.someMethod = () => console.log('Do something else ...');
component.someMethod(); // Do something else ...
```

**Comment by pedrodgfaria** [comment]
ty, for your fast reply.

i'm trying to expose a Component method, with context:

```
import {Component} from "react";
import {EventContext} from "direflow-component";
import {propTypes} from "./componentProperties";

class App extends Component {
    
    constructor(props, context) {
        super(props);
        this.state = {
            example: new Set()
        };
        this.dispatchEvent = context;
    }

    onSomeActionFromTemplate(item) {
        let {example} = this.state;
        //some code
        this.fireExampleEvent();
    }

    fireExampleEvent() {
        let {example} = this.state,
            event = new CustomEvent('example', {'detail': example});
        this.dispatchEvent(event);
    }

    @ExposedMethod
    setExampleVariable(newExampleValue) {
        this.setState({
            example: newExampleValue
        })
        this.fireExampleEvent();
    }
}

App.contextType = EventContext;
App.propTypes = propTypes;

export default App;
```

something like this, resulting in

`component.setExampleVariable(new Set(['example']))`

currently i'm using a prop 'example' passing it to state on constructor and triggering event on componentDidUpdate(if updated). 

But I think it would be nice if it was possible to expose with context.

What you think?

**Comment by Silind** [comment]
The way you are doing it with `componentDidUpdate` (or `useEffect`) is the correct approach :slightly_smiling_face: 

There are only two ways of "communicating" with the component from the outside:
Via *properties* and *attributes* and by *event-dispatching*.
This is a deliberate design choice based on the Flux principle which ensures predictability.
Introducing an exposing feature like this would potentially introduce undesired fragility to the components and Reacts lifecycle.

**Comment by pedrodgfaria** [comment]
Ok, makes sense, thanks for your attention and sharing this good project.

**Comment by kelvinwongg** [comment]
Hi @SimonHoiberg , I setup the component's method as you described above, in the .defaultProps object, I wonder how I could access the functions and properties defined inside the component?
