### ISSUE TITLE
error trying to install dependencies for initial set up

### ISSUE THREAD

**Issue by vksantoshsunny** [Silind-Software/direflow#9]
![Capture](https://user-images.githubusercontent.com/26269568/69247730-c35e4780-0c0f-11ea-8db0-0cd8210e7645.JPG)

**Comment by Silind** [comment]
Hi @vksantoshsunny 
Thank you for raising this issue.

I was able to reproduce the problem.
It seems like this is specific to npm - if you use yarn to install instead, this error does not seem to arise.

I will look into this as soon as possible.
Thank you for bringing this to my attention.

**Comment by Silind** [comment]
This issue is fixed as of direflow-cli `1.0.21` :+1:
