### ISSUE TITLE
Using material-ui plugin causes error

### ISSUE THREAD

**Issue by Silind** [Silind-Software/direflow#93]
**Describe the bug**  
Using Material UI with the material-ui plugin causes the following error:
`Warning: [JSS] Insertion point is not in the DOM`

This issue occurs when new Material UI components are dynamically added to the DOM during rerender.

**To reproduce**  
1. Create new Direflow Setup
2. Install material UI and add the plugin. [See description](https://direflow.io/plugins#material-ui)
3. Add a Material UI component as a part of a later render/rerender. (E.g. from an updated state).
4. See above error

**Expected behavior**  
Material UI components should render correctly regarding weather being part of initial render or rerendered at a later point in the application lifecycle.

**Comment by nicocunin** [comment]
I'll work on that issue, could you assign it to me pls?

**Comment by Silind** [comment]
Perfect - I have assigned you @nicocunin
